### ISSUE TITLE
Set location 

### ISSUE THREAD

**Issue by abdou-rajawi** [Altran-PT-GDC/Robot-Framework-SOAP-Library#17]
How can i **Set location** to use in future requests  when the location(s) specified in the WSDL are not correct.

For exemple : in WSDL the location of endpoint specified by default is the  Dev environment  and i should specify that the futur request should be sent to Test  Environment. and not in Dev Environment.

Thanks in advance for your help

**Comment by samuelpcabral** [comment]
The keyword **Edit XML Request** only modify the xml values. So if the location is inside your XML request, maybe you can use the XML Library of Robot Framework to edit this values:
https://robotframework.org/robotframework/latest/libraries/XML.html

Or use the **Call SOAP Method With String XML** and before this keyword, replace what you need in the "xml string".

**Comment by abdou-rajawi** [comment]
Thanks for you response.

Yes it's ok for this point, i set location inside the XML Request

<soapenv:Header>
      <To xmlns="http://www.w3.org/2005/08/addressing">**https://Endpoint here**</To>
   </soapenv:Header>  

But the probleme that when i create Soap Client, the location is'nt defined in the WSDL
<soap:address location="ToBeSpecified"/>

and when i Call SOAP Method With XML, in the XML response i have just the WSDL, and not the response of my webservice

**Comment by samuelpcabral** [comment]
@abdou-rajawi 

The only way to user the library that we build is explained in this recent issue:
https://github.com/Altran-PT-GDC/Robot-Framework-SOAP-Library/issues/18

maybe you need to edit the header or something like that...

sorry not be able to help more.
