### ISSUE TITLE
Call SOAP Method With XML not working without header

### ISSUE THREAD

**Issue by ashkank83** [Altran-PT-GDC/Robot-Framework-SOAP-Library#18]
Hi,
Thanks for this library. Would you please explain what do you mean by "the SOAP method is inside the XML file." ?
My "Call SOAP Method With XML" seems to be always failing unless I add a second parameter like below which defines the SOAPACTION in the header:
```
{'Content-Type': 'text/xml; charset=utf-8', 'SOAPAction': "http://com.abc.frontend.aaa/IFrontEndContract/createTest"}
```

**Comment by samuelpcabral** [comment]
Hi @ashkank83 
Imagine that you have a simple SOAP api. like this calculator: http://www.dneonline.com/calculator.asmx?WSDL they have 4 methods: Add, Divide, Multiply and Subtract.

In this case, as the response is very simple, you could call the method Add using as first argument of the Call SOAP Method. Like this:
```
*** Settings ***
Library           SoapLibrary

*** Test Cases ***
simple test
    Create Soap Client    http://www.dneonline.com/calculator.asmx?WSDL
    ${response}    Call SOAP Method    Add    2    3
    log    ${response}    WARN
```

But if you want call this same operation with the request in xml, the Add will be inside the xml. And your robot file would be something like this:

```
*** Settings ***
Library           SoapLibrary

*** Test Cases ***
test with xml
    Create Soap Client    http://www.dneonline.com/calculator.asmx?WSDL
    ${response}    Call SOAP Method With XML    ${CURDIR}/request.xml
    ${value}    Get Data From XML By Tag    ${response}    AddResult
    Log    ${value}    WARN
```

And your request XML should be this:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:Add>
         <tem:intA>2</tem:intA>
         <tem:intB>3</tem:intB>
      </tem:Add>
   </soapenv:Body>
</soapenv:Envelope>
```
Of course this is for simple API´s, if you have more complex API. You will probably have to manipulate the header.

Thanks.

**Comment by ashkank83** [comment]
Hi @samuelpcabral ,
Thanks for the answer, unfortunately this didn't work for me and I started using request library instead and manipulate it to call my soap API. Thanks again
