### ISSUE TITLE
Unable to validate response message with error 500

### ISSUE THREAD

**Issue by thiagosouza22** [Altran-PT-GDC/Robot-Framework-SOAP-Library#21]
Hey guys,

first thank you very much for the library.

I have a problem that when the error occurs: Request Error! Status Code: 500! Reason: Internal Server Error, I can't validate the return message.

The test is to validate a record that already exists in the database, and validation is precisely the message that returns in the response.

this is the call

![image](https://user-images.githubusercontent.com/42681813/134420221-228267b5-1871-4fb8-bae1-b8e4e6e9fc37.png)

the return message is just that

![image](https://user-images.githubusercontent.com/42681813/134420362-4ec693fb-fdcd-4abb-9917-007c1849979f.png)

using debug mode I can see the message I need to validate

![image](https://user-images.githubusercontent.com/42681813/134420605-de0c9b10-8376-4950-8ae3-3a0e2277070e.png)

soapUI response, I need to validate this message

![image](https://user-images.githubusercontent.com/42681813/134421178-77f90944-a48f-4ecf-8774-7a2a6fb6ebbd.png)

How can I get the response to validate the message when the test has the Request Error! Status Code: 500 ??

Thanks

**Comment by samuelpcabral** [comment]
@thiagosouza22 resolvido na versão 0.7, execute: pip install --upgrade robotframework-soaplibrary

**Comment by thiagosouza22** [comment]
Good morning @samuelpcabral ,

I installed the new version, but the execution continues to fail and I can't capture the return msg, do I have to do some more process?

The result I hope is not to present an error in this type of msg and to be able to retrieve the answer to validate and thus pass the test successfully.

Thanks!

![image](https://user-images.githubusercontent.com/42681813/136017091-549baabd-1c5d-4889-914b-8fc9bf61b0c7.png)


![image](https://user-images.githubusercontent.com/42681813/136017275-a720638c-009a-4d19-b1a8-166c6f431f34.png)


![image](https://user-images.githubusercontent.com/42681813/136017334-ba604297-d51f-4a7e-abb0-76907f1429c6.png)
