### ISSUE TITLE
Client TLS/SSL certificate

### ISSUE THREAD

**Issue by MichaelHallik** [Altran-PT-GDC/Robot-Framework-SOAP-Library#25]
Hi,

Thanks a lot for the library!

Greatly appreciated, (especially since the SudsLibrary seems to be no longer maintained).

I have a question:

Some SOAP-based services require a client certificate.

Is it possible to provide a service with such a certificate through the library?

Thanks in advance for any answer!

Regards,

Michael

**Comment by robinmatz** [comment]
Hi @MichaelHallik ,

I found [this link](https://docs.python-zeep.org/en/master/transport.html?highlight=certificate#tls-verification) on zeep's documentation. 

Here it says:

> Alternatively, instead of using session.verify you can use session.cert if you just want to use an TLS client certificate.

(session referes to a class object from [requests](https://docs.python-requests.org/en/latest/).

Currently, the code we have for `Create Soap Client` only supports session.verify. However, we could give it another parameter, e.g. `client_cert_location`, which would be optional and default to none. If set, the client cert location will passed to session.cert, thus enabling client certificate based authentication:
```
Create SOAP Session    ${my_endpoint}    client_cert_location=/path/to/client/cert
```

The only thing that is not clear to me right now, is if session.verify and session.cert exclude each other mutually.

**Comment by MichaelHallik** [comment]
Hello @robinmatz,

Thanks for the response.

Your solution looks good!

Indeed, I believe it would be an important enhancement to the library, since I would think that client certification is not an uncommon situation to occur when testing against a SOAP service.

Wouldn't it be strange if the two attributes would be mutually exclusive? It should be possible to validate a server and a client at the same time, shouldn't it? Do you want me to figure this out?

Regards,

Michael

**Comment by samuelpcabral** [comment]
Hi guys, as I don't have any SOAP API around here to test that you need a certificate to make the connection, I can't help at the moment, but as @robinmatz  said... the library is all based on zeep... so you can do it with zeep, we can include it in the library, if you can make the change, send the merge request and I will review it with great happiness.

**Comment by samuelpcabral** [comment]
@MichaelHallik client certificate was released in version 0.8, run pip install --upgrade robotframework-soaplibrary
Thanks for the help @robinmatz

**Comment by MichaelHallik** [comment]
@samuelpcabral 

Well, I haven't done very much. :-)

Thank you all for your swift action!

I'll test your fix a.s.a.p. at my current client's site and will let you know my findings.

Tnx again!

**Comment by MichaelHallik** [comment]
@samuelpcabral @robinmatz 

I have successfully used the new client_cert argument.

I had a .p12 certificate archive file, which was password protected. In SoapUi for instance, you can import a .p12 file, whether or  not it is pwd-protected. But with the SoapLibrary you first have to convert the file to a .pem file and remove the password in the process of doing so. For the latter you can use openSSL (comes with git for Windows, for instance).

Thank you both for the fix and your help!

**Comment by MichaelHallik** [comment]
For the whole story and (also) for a step-by-step solution, see:
