### ISSUE TITLE
XML attribute value = true is giving error

### ISSUE THREAD

**Issue by ksmyuvaraj** [Altran-PT-GDC/Robot-Framework-SOAP-Library#39]
My xml:
      <get:GetfileRequest>
         <get:ReturnObject>true</get:ReturnObject>
         <get:ReturnMD>false</get:ReturnMD>
         <get:ReturnAta>false</get:ReturnAta>
         <get:Returnlink>false</get:Returnlink>
      </get:GetfileRequest>

My Robot script:
*** Settings ***
Library    SeleniumLibrary
Library    RequestsLibrary
Library    SoapLibrary
Library    Collections
Library    XML  use_lxml=True
Library    DateTime
Library    String
Library    Process
Library    OperatingSystem

*** Test Cases ***
        Create Soap Client    ${getfile_wsdl}    ssl_verify=False
        ${response}    Call SOAP Method With XML    ${requests_dir}/request_test.xml
        ${file}    Save XML To File    ${response}    ${response_dir}    response_test

Issue is:
In XML file <get:ReturnObject>true</get:ReturnObject> 
this attribute value true is giving "XMLSyntaxError: Start tag expected, '<' not found, line 2, column 1 (<string>, line 2)"

i changed attribute value to false  <get:ReturnObject>false</get:ReturnObject> - this is not giving any error message, i am getting response file. 

i changed attribute value to TRUE<get:ReturnObject>TRUE</get:ReturnObject> - this is not giving any error message, i am getting response file.

I changed the other attribute value to true  <get:ReturnMD>true</get:ReturnMD>,   <get:ReturnAta>true</get:ReturnAta> and          <get:Returnlink>true</get:Returnlink>  - this is not giving any error message, i am getting response file.

i am getting issue only when i have xml file with <get:ReturnObject>true</get:ReturnObject>, it is giving "XMLSyntaxError: Start tag expected, '<' not found, line 2, column 1 (<string>, line 2)".

i have checked google but not finding the solution, and there is not additional spaces and any other syntax issues in xml file.

Please help me to solve this issue.

**Comment by samuelpcabral** [comment]
Hi @ksmyuvaraj can you share the whole xml file? the xml that you past in the issue is not correct.

**Comment by ksmyuvaraj** [comment]
Hi Samuel,

Thank you for your reply. below is my full xml file. 

This request is giving error: XMLSyntaxError: Start tag expected, '<' not found, line 2, column 1 (, line 2)"
if i change the value from true to True or TRUE (Capital letter) for the below two elements, request is giving response file. But this is not expected out put same behavior when i run in SoapUI.
<get:ReturnObject>True</get:ReturnObject>
<get:ReturnMetadata>True</get:ReturnMetadata>

If i run value with 'true' (small case) for these elements, SoapUi is giving expected output response file, But RBF is giving error message as mentioned above. Please help here to solve the issue.

xml file:
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:get="http://www.ergogroup.no/earchive/schemas/getdocument" xmlns:sch="http://www.ergogroup.no/earchive/schemas">
   <soapenv:Header/>
   <soapenv:Body>
      <get:GetDocumentRequest>
         <get:Authentication>
            <sch:username>MyUserName</sch:username>
            <sch:password>MyPwd</sch:password>
            <sch:externalref/>
            <sch:serviceid/>
         </get:Authentication>
         <get:ObjectId>vbr:/TestCM/InternalTest.A1001001B00I11B02Z56I1122.A22I11B02156I26022.2662/1/CONTENT</get:ObjectId>
         <get:ReturnObject>true</get:ReturnObject>
         <get:ReturnMetadata>true</get:ReturnMetadata>
         <get:ReturnAnnotations>false</get:ReturnAnnotations>
         <get:ReturnURL>false</get:ReturnURL>
      </get:GetDocumentRequest>
   </soapenv:Body>
</soapenv:Envelope>

**Comment by samuelpcabral** [comment]
@ksmyuvaraj  The code that you paste is not a valid XML, please put inside a code format, like this:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:CalcPrecoPrazo>
         <tem:nCdServico>465454</tem:nCdServico>
         <tem:sCepOrigem>564484</tem:sCepOrigem>
         <tem:sCepDestino>54644</tem:sCepDestino>
         <tem:sCdMaoPropria>N</tem:sCdMaoPropria>
         <tem:nVlValorDeclarado>0</tem:nVlValorDeclarado>
         <tem:sCdAvisoRecebimento>S</tem:sCdAvisoRecebimento>
      </tem:CalcPrecoPrazo>
   </soapenv:Body>
</soapenv:Envelope>
```

**Comment by ksmyuvaraj** [comment]
`xml file:
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:get="http://www.ergogroup.no/earchive/schemas/getdocument" xmlns:sch="http://www.ergogroup.no/earchive/schemas">
   <soapenv:Header/>
   <soapenv:Body>
      <get:GetDocumentRequest>
         <get:Authentication>
            <sch:username>MyUserName</sch:username>
            <sch:password>MyPwd</sch:password>
            <sch:externalref/>
            <sch:serviceid/>
         </get:Authentication>
         <get:ObjectId>vbr:/TestCM/InternalTest.A1001001B00I11B02Z56I1122.A22I11B02156I26022.2662/1/CONTENT</get:ObjectId>
         <get:ReturnObject>true</get:ReturnObject>
         <get:ReturnMetadata>true</get:ReturnMetadata>
         <get:ReturnAnnotations>false</get:ReturnAnnotations>
         <get:ReturnURL>false</get:ReturnURL>
      </get:GetDocumentRequest>
   </soapenv:Body>
</soapenv:Envelope>`

**Comment by ksmyuvaraj** [comment]
Please help to solve this issue

**Comment by samuelpcabral** [comment]
Hello, I testet in a public WSDL that has some boolean value.. and everything worked:

this is the test:

```
*** Settings ***
Library          SoapLibrary

*** Variables ***
${wsdl}    https://www.ebi.ac.uk/europepmc/webservices/soap?wsdl

Test02
    Create Soap Client    ${wsdl}    ssl_verify=False
    ${response}=    Call SOAP Method With XML    request.xml
    Save XML To File    ${response}    ${CURDIR}    response
```

and this is the request.xml:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://webservice.cdb.ebi.ac.uk/">
   <soapenv:Header/>
   <soapenv:Body>
      <web:profilePublications>
         <queryString>sequence</queryString>
         <profileType>all</profileType>
         <synonym>True</synonym>
      </web:profilePublications>
   </soapenv:Body>
</soapenv:Envelope>
```

I tried with "TRUE", "True" and "true"
and also with "FALSE", "False" and "false"

in all cases i received the response correct like SoapUI. In all cases the boolean value returned in small case.
You can try yourself with my code.

as I obviously don't have access to the endpoint you are testing, unfortunately I can't help.

If you know something in python you can check this two lines inside "def call_soap_method_xml"
```
        raw_text_xml = self._convert_xml_to_raw_text(xml)
        xml_obj = etree.fromstring(raw_text_xml)
```

from the reported error, it seems to me that it could be there, when reading the xml. if we really have a problem in the code.

**Comment by ksmyuvaraj** [comment]
Hi thank you for your effort in solving this issue.

I am getting response file for all inputs (true, True, TRUE), But it is not expected response file.

If I run request using soap UI: 
case 1: input value with 'true' -  is giving expected response file with all data. 
case 2: input value with 'True' or 'TRUE'  - is giving response file with success status, but it is not expected output response file (less data).

Request using RBF:
input value with 'true', 'True' and 'TRUE' - all these three input is giving response file with success status, as above case 2
I expect RBF should give response file with all data as above case1, with input value in the request with 'true', but it is not as soapui.

i have verified  these two lines in, both lines are present. 
"def call_soap_method_xml"
        raw_text_xml = self._convert_xml_to_raw_text(xml)
        xml_obj = etree.fromstring(raw_text_xml)

**Comment by samuelpcabral** [comment]
Sorry man, can´t help.. if the SoapUI is givin different results for (true, True, TRUE) your API has some error or particularity.
